default:
  navigation:
    - title: Colliers
      subtitle: Categories
      url: /t/categories/colliers
      items:
        - :title: Or
          :url: /t/categories/colliers/or
        - :title: Argent
          :url: /t/categories/colliers/argent
        - :title: Diamant
          :url: /t/categories/colliers/diamant
        - :title: Emeraude
          :url: /t/categories/colliers/emeraude
        - :title: Autres
          :url: /t/categories/colliers/autres
      promo_banners:
        - subtitle: Nouvelle collection
          title: Hiver 2020
          url: /t/collection/hiver-2020
          image: "meganav/promo_banner_left-first-category.jpg"
        - subtitle: Offres spéciales
          title: Jusqu'à 15 % de remises !
          url: /t/outlet/15-pourcents-de-remises
          image: "meganav/promo_banner_right-first-category.jpg"
    - title: Bagues
      subtitle: Categories
      url: /t/categories/bagues
      items:
        - :title: Or
          :url: /t/categories/bagues/or
        - :title: Or blanc
          :url: /t/categories/bagues/or-blanc
        - :title: Or rose
          :url: /t/categories/bagues/or-rose
        - :title: Argent
          :url: /t/categories/bagues/argent
      promo_banners:
        - subtitle: Nouvelle collection
          title: Hiver 2020
          url: /t/categories/collection/hiver-2020
          image: "meganav/promo_banner_left-second-category.jpg"
        - subtitle: Offres spéciales
          title: Jusqu'à 15 % de remises !
          url: /t/categories/outlet/15-pourcents-de-remises
          image: "meganav/promo_banner_right-second-category.jpg"
    - title: Collection
      subtitle: Categories
      url: /t/categories/collection
      items:
        - :title: Peace and love
          :url: /t/categories/collection/peace-and-love
        - :title: Flower
          :url: /t/categories/collection/flower
        - :title: Ocean
          :url: /t/categories/collection/ocean
        - :title: Hiver 2020
          :url: /t/categories/collection/hiver-2020
      promo_banners:
        - subtitle: Nouvelle collection
          title: Hiver 2020
          url: /t/categories/collection/hiver-2020
          image: "meganav/promo_banner_left-third-category.jpg"
        - subtitle: Offres spéciales
          title: Jusqu'à 15 % de remises !
          url: /t/categories/outlet/15-pourcents-de-remises
          image: "meganav/promo_banner_right-third-category.jpg"
    - title: Outlet
      subtitle: Categories
      url: /t/categories/outlet
      items:
        - :title: Jusqu'à 30 % de remises
          :url: /t/categories/outlet/30-pourcents-de-remises
        - :title: Jusqu'à 50 % de remises
          :url: /t/categories/outlet/50-pourcents-de-remises
      promo_banners:
        - subtitle: Trouvez la perle rare
          title: Bon plans
          url: /t/categories/collection/hiver-2020
          image: "meganav/promo_banner_left-forth-category.jpg"
        - subtitle: Les supers promo
          title: Jusqu'à 50 % de remises !
          url: /t/categories/outlet/offre-spéciale
          image: "meganav/promo_banner_right-forth-category.jpg"
    - title: Cadeaux
      subtitle: Categories
      url: /t/categories/cadeaux
      items:
        - :title: Carte cadeaux
          :url: /categories/cadeaux/carte-cadeaux
        - :title: Bijoux personnalisé
          :url: /t/categories/cadeaux/bijoux-personnalise
        - :title: Pour lui
          :url: /t/categories/cadeaux/pour-lui
        - :title: Pour elle
          :url: /t/categories/cadeaux/pour-elle
        - :title: Pour couple
          :url: /t/categories/cadeaux/pour-couple
      promo_banners:
        - subtitle: Trouvez le cadeaux idéale
          title: Best-seller
          url: /t/cadeaux
          image: "meganav/promo_banner_left-fifth-category.jpg"
        - subtitle: Les supers promo
          title: Jusqu'à 50 % de remises !
          url: /t/categories/outlet/50-pourcents-de-remises
          image: "meganav/promo_banner_right-fifth-category.jpg"
    - title: Tendances
      subtitle: Categories
      url: /t/categories/tendances
      items:
        - :title: Pour elle
          :url: /t/categories/tendances/pour-elle
        - :title: Pour lui
          :url: /t/categories/tendances/pour-lui
      promo_banners:
        - subtitle: Nouvelle collection
          title: Hiver 2020
          url: /t/categories/collection/hiver-2020
          image: "meganav/promo_banner_left-sixth-category.jpg"
        - subtitle: Offres spéciales
          title: Jusqu'à 15 % de remises !
          url: /t/categories/outlet/offre-spéciale
          image: "meganav/promo_banner_right-sixth-category.jpg"
